version: '3'

services:
  neo:
    image: neo4j:3.5.14-enterprise
    ports: 
      - 7474:7474
      - 7687:7687
    expose: 
      - 7474
    environment: 
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_AUTH: "neo4j/test"
      NEO4JLABS_PLUGINS: "[\"apoc\"]"
    volumes:
      - "./neo4j/data:/data"
      - "./neo4j/conf:/conf"
      - "./neo4j/plugins:/plugins"
      - "./neo4j/import:/import"
      - "./neo4j/logs:/logs"
    networks: [bdt]
  
  flask:
    build: 
      context: ./flask
      dockerfile: Dockerfile
    ports: 
      - 5000:5000
    volumes:
      - "./flask:/usr/src/app"
    networks: [bdt]
  
  react:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports: 
      - 80:3000
    networks: [bdt]
    volumes: 
      - "./client:/app"
      - "./client/app/node_modules"
    stdin_open: true
  
  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks: [bdt]
    volumes:
      - "./redis-data:/data"
  
  ltc:
    build:
      context: ./ltc
      dockerfile: Dockerfile
    hostname: ltc
    networks: [bdt]
networks: 
  bdt:
